<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Proyecto;

class ProyectoSeeder extends Seeder
{
    public function run(): void
    {
        Proyecto::truncate();

        $obras = [
            ['nombre' => 'Montaje Eléctrico Edificio Sarmiento', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Inmobiliaria', 'mandante' => 'Inmobiliaria Patagónica', 'categoria' => 'Eléctrica', 'lat' => -53.157474, 'lng' => -70.899199, 'año' => 2008, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Calle Sarmiento, sector centro Punta Arenas'],
            ['nombre' => 'Montaje Eléctrico Condominio La Estancia Etapa I', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'BISAL', 'mandante' => 'Inmobiliaria Salfa Austral', 'categoria' => 'Eléctrica', 'lat' => -53.1417, 'lng' => -70.895, 'año' => 2009, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Sector Río de la Mano / La Estancia, Punta Arenas'],
            ['nombre' => 'Fiscalía Regional', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'Ministerio de Justicia', 'categoria' => 'Institucional', 'lat' => -45.5717, 'lng' => -72.0689, 'año' => 2009, 'region' => 'XI', 'comuna' => 'Coyhaique', 'direccion' => '21 de Mayo 605, Coyhaique'],
            ['nombre' => 'Montaje Eléctrico Hotel Costa Australis', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Salfa S.A.', 'mandante' => 'Hotel Costa Australis', 'categoria' => 'Turismo', 'lat' => -51.7298, 'lng' => -72.5078, 'año' => 2009, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Pedro Montt 262, Puerto Natales'],
            ['nombre' => 'Condominio La Estancia Etapa II', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'BISAL', 'mandante' => 'Inmobiliaria Salfa Austral', 'categoria' => 'Eléctrica', 'lat' => -53.1417, 'lng' => -70.895, 'año' => 2009, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Sector Río de la Mano / La Estancia, Punta Arenas'],
            ['nombre' => 'Polideportivo 18 de Septiembre', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Constructora Bravo e Izquierdo Ltda.', 'mandante' => 'MOP', 'categoria' => 'Deportivo', 'lat' => -53.1422, 'lng' => -70.8989, 'año' => 2010, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. José Martínez de Aldunate s/n, Punta Arenas'],
            ['nombre' => 'Municipalidad de Puerto Natales', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'MOP', 'categoria' => 'Institucional', 'lat' => -51.7236, 'lng' => -72.5089, 'año' => 2010, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Eberhard 457, Puerto Natales'],
            ['nombre' => 'Hotel Museo Puerto Bories', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'The Singular Hotel (Sociedad Puerto Bories)', 'categoria' => 'Turismo', 'lat' => -51.6997, 'lng' => -72.5161, 'año' => 2010, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Km 5,5 Norte s/n, Puerto Bories, Puerto Natales'],
            ['nombre' => 'Polideportivo Puerto Aysén', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles, CCTV, audio, detección de incendio y cableado estructurado', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'MOP', 'categoria' => 'Deportivo', 'lat' => -45.4036, 'lng' => -72.6932, 'año' => 2011, 'region' => 'XI', 'comuna' => 'Puerto Aysén', 'direccion' => 'Av. Benigno Díaz 15, Puerto Aysén'],
            ['nombre' => 'Hotel Tierra Patagonia', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'Hotel Tierra Patagonia', 'categoria' => 'Turismo', 'lat' => -50.9667, 'lng' => -72.7333, 'año' => 2011, 'region' => 'XII', 'comuna' => 'Torres del Paine', 'direccion' => 'Sector Lago Sarmiento, P.N. Torres del Paine'],
            ['nombre' => 'Regimiento Cía. Andina Cochrane', 'descripcion' => 'Instalaciones eléctricas y de corrientes débiles', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'Ejército de Chile', 'categoria' => 'Institucional', 'lat' => -47.2536, 'lng' => -72.5723, 'año' => 2011, 'region' => 'XI', 'comuna' => 'Cochrane', 'direccion' => 'Compañía Andina N°20, Cochrane'],
            ['nombre' => 'Urbanización Minera Isla Riesco', 'descripcion' => 'Obras eléctricas de fuerza e instalación de generadores. Suministro y fabricación de sala eléctrica', 'cliente' => 'RCFR Ltda.', 'mandante' => 'Sociedad Minera Isla Riesco', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2011, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Km 40 Ruta Y-560, Isla Riesco'],
            ['nombre' => 'Casas Km 4,5 Sur', 'descripcion' => 'Construcción eléctrica total de 3 casas', 'cliente' => 'Inmobiliaria Vista al Bosque', 'mandante' => 'Inmobiliaria Vista al Bosque', 'categoria' => 'Eléctrica', 'lat' => -53.205, 'lng' => -70.905, 'año' => 2012, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Km 4,5 Sur, Ruta 9, Punta Arenas'],
            ['nombre' => 'PTAP Aguas Magallanes Porvenir', 'descripcion' => 'Instalaciones de control y fuerza, puesta en servicio de planta de agua potable', 'cliente' => 'Aguas Magallanes', 'mandante' => 'Aguas Magallanes', 'categoria' => 'Industrial', 'lat' => -53.2956, 'lng' => -70.3656, 'año' => 2012, 'region' => 'XII', 'comuna' => 'Porvenir', 'direccion' => 'Planta de Agua Potable Aguas Magallanes, Porvenir'],
            ['nombre' => 'Oficina Enertecs', 'descripcion' => 'Instalaciones eléctricas oficina Enertecs', 'cliente' => 'Inmobiliaria Vista al Bosque', 'mandante' => 'Inmobiliaria Vista al Bosque', 'categoria' => 'Eléctrica', 'lat' => -53.205, 'lng' => -70.905, 'año' => 2012, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Sector Loteo Vista al Bosque, Punta Arenas'],
            ['nombre' => 'Mina Invierno Zona 100 y 300', 'descripcion' => 'Instalación eléctrica de fuerza y corrientes débiles. Área de oficina, laboratorio y recreación minera', 'cliente' => 'Constructora Salfa S.A.', 'mandante' => 'Sociedad Minera Isla Riesco', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2012, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Faena Mina Invierno, Km 40 Ruta Y-560, Isla Riesco'],
            ['nombre' => 'Aumento de Capacidad Eléctrica Muelle Mardones', 'descripcion' => 'Instalaciones eléctricas media tensión, montaje de subestación, reconectadores y celdas de media tensión', 'cliente' => 'Empresa Portuaria Austral', 'mandante' => 'Empresa Portuaria Austral', 'categoria' => 'Portuaria', 'lat' => -53.1722, 'lng' => -70.9028, 'año' => 2012, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Muelle José de los Santos Mardones, EPA Austral, Punta Arenas'],
            ['nombre' => 'Montaje de Cargadores de Carbón', 'descripcion' => 'Instalaciones de fuerza, control e instrumentación cargador de carbón Mina Invierno. Obra en plataforma marítima', 'cliente' => 'FAM Chile Ltda.', 'mandante' => 'Sociedad Minera Isla Riesco', 'categoria' => 'Minería', 'lat' => -52.79, 'lng' => -71.74, 'año' => 2012, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Muelle Mina Invierno (Otway), Isla Riesco'],
            ['nombre' => 'Normalización Instalación Eléctrica Colegio INSAFA', 'descripcion' => 'Normalización eléctrica de instalaciones', 'cliente' => 'Colegio INSAFA', 'mandante' => 'Colegio INSAFA', 'categoria' => 'Educacional', 'lat' => -53.1631, 'lng' => -70.9097, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Mejicana 830, Punta Arenas'],
            ['nombre' => 'CCTV Muelle, Cargadores y Stock Pile Mina Invierno', 'descripcion' => 'CCTV muelle, cargadores de barco y stock pile en Mina Invierno (ambiente marítimo)', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.79, 'lng' => -71.74, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Muelle y Stock Pile Mina Invierno, Isla Riesco'],
            ['nombre' => 'CCTV SMIR Mina Invierno', 'descripcion' => 'Sistema CCTV SMIR en Mina Invierno', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Alimentador Estancia Cañadón', 'descripcion' => 'Alimentador eléctrico Estancia Cañadón, Isla Riesco', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.85, 'lng' => -71.55, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Estancia Cañadón, Isla Riesco'],
            ['nombre' => 'Instalación Portón Acceso y Vigilancia Central Providencia', 'descripcion' => 'Automatización de portón, canalización, cableado e instalación de escalerillas', 'cliente' => 'Hidromaule', 'mandante' => 'Hidromaule', 'categoria' => 'Industrial', 'lat' => -35.58, 'lng' => -71.0833, 'año' => 2013, 'region' => 'VII', 'comuna' => 'San Clemente', 'direccion' => 'Central Providencia, sector Vilches Alto, San Clemente'],
            ['nombre' => 'Tendido Línea MT Campamento Mina Invierno', 'descripcion' => 'Tendido línea campamento 1, subestación 750 KVA, celdas MT, generador 600 KVA, normalización tableros', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Galpón Finning Mina Invierno', 'descripcion' => 'Instalación eléctrica galpón Finning en Mina Invierno', 'cliente' => 'Finning', 'mandante' => 'Finning', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Galpón Finning, Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Mantención Eléctrica Hotel Llanuras de Diana', 'descripcion' => 'Trabajos y mantención eléctrica Hotel Llanuras de Diana', 'cliente' => 'Hotel Llanuras de Diana', 'mandante' => 'Hotel Llanuras de Diana', 'categoria' => 'Turismo', 'lat' => -51.93, 'lng' => -72.4067, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Ruta 9 Km 215, Sector Cerro Castillo, Puerto Natales'],
            ['nombre' => 'Malla de Tierra Galpón y Contenedores Finning', 'descripcion' => 'Malla de tierra galpón y contenedores Finning, Mina Invierno', 'cliente' => 'Finning', 'mandante' => 'Finning', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Galpón Finning, Mina Invierno, Isla Riesco'],
            ['nombre' => 'Instalación Eléctrica Laboratorio Weatherford', 'descripcion' => 'Instalación eléctrica laboratorio Weatherford', 'cliente' => 'Weatherford', 'mandante' => 'Weatherford', 'categoria' => 'Industrial', 'lat' => -53.1614, 'lng' => -70.9075, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Lautaro Navarro 739, Punta Arenas'],
            ['nombre' => 'Sistema de Comunicación Antena Puerto Mina Invierno', 'descripcion' => 'Conexión a la red y suministro de UPS para equipos de comunicación antena puerto en Mina Invierno', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.79, 'lng' => -71.74, 'año' => 2013, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Antena Puerto Mina Invierno, Isla Riesco'],
            ['nombre' => 'Centro de Rehabilitación', 'descripcion' => 'Instalaciones eléctricas y corrientes débiles, montajes', 'cliente' => 'Salfa S.A.', 'mandante' => 'Servicio de Salud', 'categoria' => 'Salud', 'lat' => -53.1786, 'lng' => -70.9075, 'año' => 2014, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Eduardo Frei 02281, Punta Arenas'],
            ['nombre' => 'Planta de Agua Guanaco 4', 'descripcion' => 'Ejecución obras de montaje eléctrico', 'cliente' => 'Petrotech', 'mandante' => 'Geopark', 'categoria' => 'Industrial', 'lat' => -52.45, 'lng' => -69.45, 'año' => 2014, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Bloque Fell, Campo Guanaco, sector sur Magallanes'],
            ['nombre' => 'Tendido Línea MT Soterramiento Mina Invierno', 'descripcion' => 'Soterramiento línea MT cruce de camino', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2014, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Montaje S/E 10KVA Mina Invierno', 'descripcion' => 'Instalación y puesta en servicio de subestación', 'cliente' => 'SMIR', 'mandante' => 'SMIR', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2014, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Montaje Ventilador Laboratorio Intertek', 'descripcion' => 'Instalación de extractor explosión proof', 'cliente' => 'Intertek', 'mandante' => 'Intertek', 'categoria' => 'Industrial', 'lat' => -53.147939, 'lng' => -70.902383, 'año' => 2014, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Laboratorio Intertek, Punta Arenas'],
            ['nombre' => 'Centro de Salud Familiar Hospital Puerto Williams', 'descripcion' => 'Instalaciones eléctricas, control centralizado y corrientes débiles', 'cliente' => 'Salfa S.A.', 'mandante' => 'Servicio de Salud', 'categoria' => 'Salud', 'lat' => -54.9347, 'lng' => -67.6131, 'año' => 2015, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => "O'Higgins 246, Puerto Williams (Hospital Comunitario Cristina Calderón)"],
            ['nombre' => 'Ampliación de Potencia Muelle Mardones', 'descripcion' => 'Ampliación en 1,25 MVA para contenedores reefer (ambiente marítimo)', 'cliente' => 'Empresa Portuaria Austral', 'mandante' => 'EPA', 'categoria' => 'Portuaria', 'lat' => -53.1722, 'lng' => -70.9028, 'año' => 2015, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Muelle José de los Santos Mardones, EPA Austral, Punta Arenas'],
            ['nombre' => 'Mantención Líneas y Equipos de Media Tensión Mina Invierno', 'descripcion' => 'Mantenimiento eléctrico de sistemas de media tensión, incluye mantención del sistema de cargador Sheep Loader', 'cliente' => 'Mina Invierno', 'mandante' => 'Mina Invierno y Área Muelle', 'categoria' => 'Minería', 'lat' => -52.79, 'lng' => -71.74, 'año' => 2015, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Mina Invierno y Muelle, Isla Riesco'],
            ['nombre' => 'Ampliación Muelle Prat', 'descripcion' => 'Ampliación de obras portuarias Muelle Prat, obras eléctricas y de comunicaciones navales', 'cliente' => 'EPA Austral', 'mandante' => 'EPA Austral', 'categoria' => 'Portuaria', 'lat' => -53.1556, 'lng' => -70.9089, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => "Terminal Arturo Prat, Av. Bernardo O'Higgins, Punta Arenas"],
            ['nombre' => 'Centro Clínico de Imagenología IMET', 'descripcion' => 'Construcción de obras de ingeniería eléctrica, seguridad y corrientes débiles en clínica de imagenología', 'cliente' => 'IMET', 'mandante' => 'Los Cipreses', 'categoria' => 'Salud', 'lat' => -53.1192, 'lng' => -70.8881, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Manuel Bulnes 04236, Punta Arenas'],
            ['nombre' => 'Mantención Generadores Unimarc Puerto Natales', 'descripcion' => 'Mantención de 1 generador de respaldo supermercados Unimarc', 'cliente' => 'Unimarc', 'mandante' => 'SMU', 'categoria' => 'Comercial', 'lat' => -51.7244, 'lng' => -72.5061, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Locales Unimarc/SMU, Puerto Natales'],
            ['nombre' => 'Mantención Generadores Unimarc Punta Arenas', 'descripcion' => 'Mantención de 10 generadores de respaldo supermercados Unimarc', 'cliente' => 'Unimarc', 'mandante' => 'SMU', 'categoria' => 'Comercial', 'lat' => -53.1638, 'lng' => -70.9171, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Locales Unimarc/SMU, Punta Arenas (10 supermercados)'],
            ['nombre' => 'Reconstrucción Planta Molienda Algina (Infraestructura)', 'descripcion' => 'Obras de infraestructura eléctrica planta de molienda', 'cliente' => 'Productos Químicos Algina', 'mandante' => 'Productos Químicos Algina', 'categoria' => 'Industrial', 'lat' => -53.3008, 'lng' => -70.4167, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Porvenir', 'direccion' => 'Sector Bahía Chilota, Porvenir'],
            ['nombre' => 'Reconstrucción Planta Molienda Algina (Motores)', 'descripcion' => 'Suministro y mantenimiento de motores eléctricos', 'cliente' => 'Productos Químicos Algina', 'mandante' => 'Productos Químicos Algina', 'categoria' => 'Industrial', 'lat' => -53.3008, 'lng' => -70.4167, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Porvenir', 'direccion' => 'Sector Bahía Chilota, Porvenir'],
            ['nombre' => 'Mantención Generador 111J Methanex', 'descripcion' => 'Mantención eléctrica y mediciones de generador turbina de gas, Planta Methanex Chile', 'cliente' => 'Methanex', 'mandante' => 'Methanex', 'categoria' => 'Industrial', 'lat' => -52.9461, 'lng' => -70.8569, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Ruta 9 Norte Km 28,5, Sector Cabo Negro, Punta Arenas'],
            ['nombre' => 'Centro Deportivo Integral', 'descripcion' => 'Obras eléctricas y corrientes débiles, iluminación DALI', 'cliente' => 'Constructora Salfa', 'mandante' => 'Instituto Nacional del Deporte', 'categoria' => 'Deportivo', 'lat' => -53.1561, 'lng' => -70.9125, 'año' => 2016, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Uruguay 1448, Punta Arenas'],
            ['nombre' => 'Centro Clínico de Imágenes Scanner Sur', 'descripcion' => 'Instalaciones eléctricas de potencia, corrientes débiles y control centralizado', 'cliente' => 'Constructora Salfa', 'mandante' => 'Inversiones Framura Ltda.', 'categoria' => 'Salud', 'lat' => -53.1497, 'lng' => -70.9069, 'año' => 2017, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Manuel Bulnes 01448, Punta Arenas'],
            ['nombre' => 'Antena Satelital KSAT - Sala de Generación', 'descripcion' => 'Suministro de sala de generación con TTA sincronizado', 'cliente' => 'Chillean Satellite Ground Station Punta Arenas SpA', 'mandante' => 'Kongsberg KSAT', 'categoria' => 'Telecomunicaciones', 'lat' => -52.93569, 'lng' => -70.870149, 'año' => 2017, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Estación Satelital KSAT, Punta Arenas'],
            ['nombre' => 'Antena Satelital KSAT - Línea MT 13,2KV', 'descripcion' => 'Ejecución línea de media tensión 13,2KV', 'cliente' => 'Chillean Satellite Ground Station Punta Arenas SpA', 'mandante' => 'Kongsberg KSAT', 'categoria' => 'Telecomunicaciones', 'lat' => -52.93569, 'lng' => -70.870149, 'año' => 2017, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Estación Satelital KSAT, Punta Arenas'],
            ['nombre' => 'Antena Satelital KSAT - Obras Eléctricas y Enlaces', 'descripcion' => 'Ingeniería y ejecución de obras eléctricas de potencia y enlaces', 'cliente' => 'Chillean Satellite Ground Station Punta Arenas SpA', 'mandante' => 'Kongsberg KSAT', 'categoria' => 'Telecomunicaciones', 'lat' => -52.93569, 'lng' => -70.870149, 'año' => 2017, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Estación Satelital KSAT, Punta Arenas'],
            ['nombre' => 'Centro Asistencial Docente e Investigación UMAG', 'descripcion' => 'Obras eléctricas, corrientes débiles y control centralizado para edificio de 9.800 m²', 'cliente' => 'Constructora Salfa', 'mandante' => 'MOP', 'categoria' => 'Educacional', 'lat' => -53.1419, 'lng' => -70.8939, 'año' => 2017, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Los Flamencos 01364, Punta Arenas'],
            ['nombre' => 'Edificio CADI - Solar OFF-GRID 12,72 kWp', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 12,72 kWp (TE-1 N°1889321)', 'cliente' => 'MOP - Dirección de Arquitectura', 'mandante' => 'MOP', 'categoria' => 'Solar', 'lat' => -53.1419, 'lng' => -70.8939, 'año' => 2018, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Los Flamencos 01364, Punta Arenas'],
            ['nombre' => 'Captación de Aguas Subterráneas Magelan', 'descripcion' => 'Alimentación de fuerza de 5 pozos profundos automatizados con comunicación inalámbrica y PLC SCADA', 'cliente' => 'Magelan Antartic Gel', 'mandante' => 'Magelan Antartic Gel', 'categoria' => 'Industrial', 'lat' => -53.2942, 'lng' => -70.3683, 'año' => 2018, 'region' => 'XII', 'comuna' => 'Porvenir', 'direccion' => 'Capitanía 075, Bahía Chilota, Porvenir'],
            ['nombre' => 'Normalización Edificios Gasco Magallanes', 'descripcion' => 'Normalización eléctrica de instalaciones existentes', 'cliente' => 'Gasco Magallanes', 'mandante' => 'Gasco Magallanes', 'categoria' => 'Industrial', 'lat' => -53.1583, 'lng' => -70.9111, 'año' => 2018, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => "Av. Bernardo O'Higgins 860, Punta Arenas"],
            ['nombre' => 'Bowling Strike 12', 'descripcion' => 'Obras eléctricas y corrientes débiles para Bowling Strike 12', 'cliente' => 'Andigraf', 'mandante' => 'Andigraf', 'categoria' => 'Comercial', 'lat' => -53.1383, 'lng' => -70.8997, 'año' => 2018, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Centro Comercial Zona Austral, Av. Frei, Punta Arenas'],
            ['nombre' => 'Edificio Comapa - Hoteles Australis', 'descripcion' => 'Obras eléctricas y corrientes débiles Edificio Comapa', 'cliente' => 'Constructora Bravo e Izquierdo', 'mandante' => 'Hoteles Australis', 'categoria' => 'Turismo', 'lat' => -53.1606, 'lng' => -70.9089, 'año' => 2018, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Hernando de Magallanes 990, Punta Arenas'],
            ['nombre' => 'Transpetrol - Estación de Combustibles Tehuelches', 'descripcion' => 'Obras eléctricas a prueba de explosión, estación de combustibles', 'cliente' => 'Transpetrol', 'mandante' => 'Transpetrol', 'categoria' => 'Industrial', 'lat' => -52.9217, 'lng' => -70.9092, 'año' => 2018, 'region' => 'XII', 'comuna' => 'Tehuelches', 'direccion' => 'Ruta 9 Norte Km 53, sector Villa Tehuelches'],
            ['nombre' => 'Mantenimiento Mina Invierno - Transformador y Seccionador', 'descripcion' => 'Instalación de transformador y seccionador Mina Invierno', 'cliente' => 'Mina Invierno', 'mandante' => 'Mina Invierno', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Isla Riesco', 'direccion' => 'Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Mantenimiento Mina Invierno - Línea 23KV', 'descripcion' => 'Mantenimiento de línea de 23KV, transformador y subestación Mina Invierno', 'cliente' => 'Mina Invierno', 'mandante' => 'Mina Invierno', 'categoria' => 'Minería', 'lat' => -52.7717, 'lng' => -71.7344, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Isla Riesco', 'direccion' => 'Faena Mina Invierno, Isla Riesco'],
            ['nombre' => 'Centro Recreacional Río Rubens - Solar OFF-GRID 3,0 kWp', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp', 'cliente' => 'Constructora Salfa', 'mandante' => 'Constructora Salfa', 'categoria' => 'Solar', 'lat' => -52.0167, 'lng' => -71.8917, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Sector Río Rubens, Ruta 9, Puerto Natales'],
            ['nombre' => 'Centro Subantártico Puerto Williams', 'descripcion' => 'Obras eléctricas y corrientes débiles, control centralizado para edificio Centro Subantártico', 'cliente' => 'Constructora Salfa', 'mandante' => 'MOP', 'categoria' => 'Institucional', 'lat' => -54.9347, 'lng' => -67.6131, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => "O'Higgins 310, Puerto Williams"],
            ['nombre' => 'Jardín Infantil JUNJI Puerto Williams', 'descripcion' => 'Obras eléctricas y corrientes débiles jardín infantil JUNJI', 'cliente' => 'Constructora Salfa', 'mandante' => 'JUNJI', 'categoria' => 'Educacional', 'lat' => -54.9333, 'lng' => -67.6167, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Jardín Infantil JUNJI, Puerto Williams'],
            ['nombre' => 'Centro Subantártico Cabo de Hornos - Eólico 20 kWp', 'descripcion' => 'Proyecto eólico 20 kWp (TE-1 N°2385682)', 'cliente' => 'MOP - Dirección de Arquitectura', 'mandante' => 'MOP', 'categoria' => 'Solar', 'lat' => -54.9347, 'lng' => -67.6131, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => "O'Higgins 310, Puerto Williams"],
            ['nombre' => 'Centro Subantártico Cabo de Hornos - Solar 19,8 kWp', 'descripcion' => 'Proyecto fotovoltaico 19,8 kWp (TE-1 N°2385682)', 'cliente' => 'MOP - Dirección de Arquitectura', 'mandante' => 'MOP', 'categoria' => 'Solar', 'lat' => -54.9347, 'lng' => -67.6131, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => "O'Higgins 310, Puerto Williams"],
            ['nombre' => 'Centro de Rehabilitación Cruz del Sur - Solar OFF-GRID 17 kWp', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 17 kWp (TE-1 N°1200962)', 'cliente' => 'Servicio de Salud Magallanes', 'mandante' => 'Servicio Salud Magallanes', 'categoria' => 'Solar', 'lat' => -53.1786, 'lng' => -70.9075, 'año' => 2019, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Eduardo Frei 02281, Punta Arenas'],
            ['nombre' => 'Instalación Fotovoltaica OFF-GRID Estancia Tita, Isla Riesco', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2235900)', 'cliente' => 'Peter Maclean Muñoz', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -52.85069, 'lng' => -71.510674, 'año' => 2020, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Estancia Tita, Isla Riesco'],
            ['nombre' => 'Instalación Fotovoltaica OFF-GRID Estancia Adela, Isla Riesco', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 5,0 kWp (TE-1 N°2235883)', 'cliente' => 'Peter Maclean Boyd', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -52.85, 'lng' => -71.55, 'año' => 2020, 'region' => 'XII', 'comuna' => 'Río Verde', 'direccion' => 'Estancia Adela, Isla Riesco'],
            ['nombre' => 'Instalación Fotovoltaica OFF-GRID Ganadera Vista El Bosque', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 5,0 kWp (TE-1 N°2229753)', 'cliente' => 'Agrícola y Ganadera ANP EIRL', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -53.205, 'lng' => -70.905, 'año' => 2020, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Sector Loteo Vista al Bosque, Punta Arenas'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID para riego hortalizas', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp para sistema de riego (TE-1 N°2589290)', 'cliente' => 'María Agüero Díaz', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -53.1547, 'lng' => -70.9081, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Manuel Bulnes 309, Edificio del Agro, Punta Arenas'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Huertos Familiares - Soto', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2597049)', 'cliente' => 'Germán Soto Anguita', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.935704, 'lng' => -67.574042, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Huertos Familiares, Puerto Williams (Isla Navarino)'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Ensenada Villarino', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598285)', 'cliente' => 'Javier Godoy Chávez', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.9333, 'lng' => -67.6167, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Ensenada Villarino, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Huertos Familiares - Subiabre', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598375)', 'cliente' => 'José Subiabre Subiabre', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.935704, 'lng' => -67.574042, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Huertos Familiares, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Seno Lauta', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598845)', 'cliente' => 'Katherine Morales Urrutia', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.935171, 'lng' => -67.649748, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Seno Lauta, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Huertos Familiares - Barría', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598844)', 'cliente' => 'Luis Barría Legue', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.935704, 'lng' => -67.574042, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Huertos Familiares, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Santa Rosa - Puerto Williams', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598854)', 'cliente' => 'María Muñoz Manquemilla', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.903871, 'lng' => -68.156664, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Santa Rosa, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Huertos Familiares - Muñoz Ulloa', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598870)', 'cliente' => 'María Muñoz Ulloa', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.935704, 'lng' => -67.574042, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Huertos Familiares, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Corrales Viejos - Puerto Williams', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2601620)', 'cliente' => 'Delfo Muñoz Muñoz', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.9333, 'lng' => -67.6167, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Corrales Viejos, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Los Pioneros - Puerto Williams', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2598984)', 'cliente' => 'Nelson Guenel González', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.9333, 'lng' => -67.6167, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Los Pioneros, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico OFF-GRID Lote Waif - Puerto Williams', 'descripcion' => 'Proyecto fotovoltaico OFF-GRID 3,0 kWp (TE-1 N°2607384)', 'cliente' => 'Roberto Filgueira Martínez', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -54.920737, 'lng' => -68.216449, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Williams', 'direccion' => 'Sector Lote Waif, Puerto Williams'],
            ['nombre' => 'Sistema Fotovoltaico ON-GRID producción hortícola - Sierpe', 'descripcion' => 'Proyecto fotovoltaico ON-GRID 3,0 kWp (TE-4 N°2662946)', 'cliente' => 'María Bernardita Sierpe', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -53.1547, 'lng' => -70.9081, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Manuel Bulnes 309, Edificio del Agro, Punta Arenas'],
            ['nombre' => 'Sistema Fotovoltaico ON-GRID producción hortalizas - Delgado', 'descripcion' => 'Proyecto fotovoltaico ON-GRID 3,0 kWp (TE-4 en trámite)', 'cliente' => 'Patricia Delgado Navarro', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -53.1547, 'lng' => -70.9081, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Manuel Bulnes 309, Edificio del Agro, Punta Arenas'],
            ['nombre' => 'Sistema Fotovoltaico ON-GRID producción hortalizas - Cárdenas', 'descripcion' => 'Proyecto fotovoltaico ON-GRID 3,0 kWp (TE-4 N°2662989)', 'cliente' => 'Rosa Cárdenas Téllez', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -53.1547, 'lng' => -70.9081, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Punta Arenas', 'direccion' => 'Av. Manuel Bulnes 309, Edificio del Agro, Punta Arenas'],
            ['nombre' => 'Sistema Fotovoltaico ON-GRID Huerto N°259-2B, Puerto Natales', 'descripcion' => 'Proyecto fotovoltaico ON-GRID 3,0 kWp (TE-4 N°2663004)', 'cliente' => 'Orita Teca Lepio', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -51.7236, 'lng' => -72.5067, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Sector Huertos Familiares, Puerto Natales'],
            ['nombre' => 'Sistema Fotovoltaico ON-GRID Huerto N°62, Puerto Natales', 'descripcion' => 'Proyecto fotovoltaico ON-GRID 3,0 kWp (TE-4 N°2663779)', 'cliente' => 'María Villegas Barría', 'mandante' => 'Secretaría Regional de Agricultura', 'categoria' => 'Solar', 'lat' => -51.7236, 'lng' => -72.5067, 'año' => 2021, 'region' => 'XII', 'comuna' => 'Puerto Natales', 'direccion' => 'Sector Huertos Familiares, Puerto Natales'],
        ];

        foreach ($obras as $obra) {
            Proyecto::create(array_merge($obra, ['activo' => true]));
        }
    }
}
