---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/enertecs-laravel
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
